/* eslint-disable */
export const district = [{
	"value": "123123",
	"title": "只有一级",
}, {
	"value": "340000",
	"title": "安徽省",
	"children": [{
		"value": "341500",
		"title": "六安市",
		"children": [{
			"value": "341522",
			"title": "霍邱县",
			"children": []
		}, {
			"value": "341525",
			"title": "霍山县",
			"children": []
		}, {
			"value": "341502",
			"title": "金安区",
			"children": []
		}, {
			"value": "341524",
			"title": "金寨县",
			"children": []
		}, {
			"value": "341526",
			"title": "其它区",
			"children": []
		}, {
			"value": "341521",
			"title": "寿县",
			"children": []
		}, {
			"value": "341523",
			"title": "舒城县",
			"children": []
		}, {
			"value": "341503",
			"title": "裕安区",
			"children": []
		}]
	}, {
		"value": "340500",
		"title": "马鞍山市",
		"children": [{
			"value": "340506",
			"title": "博望区",
			"children": []
		}]
	}, {
		"value": "341800",
		"title": "宣城市",
		"children": [{
			"value": "341822",
			"title": "广德县",
			"children": []
		}, {
			"value": "341824",
			"title": "绩溪县",
			"children": []
		}, {
			"value": "341825",
			"title": "旌德县",
			"children": []
		}]
	}]
}, {
	"value": "820000",
	"title": "澳门特别行政区",
	"children": [{
		"value": "820100",
		"title": "澳门半岛",
		"children": []
	}, {
		"value": "820200",
		"title": "离岛",
		"children": []
	}]
}, {
	"value": "110000",
	"title": "北京",
	"children": [{
		"value": "110100",
		"title": "北京市",
		"children": [{
			"value": "110114",
			"title": "昌平区",
			"children": []
		}, {
			"value": "110105",
			"title": "朝阳区",
			"children": []
		}, {
			"value": "110103",
			"title": "崇文区",
			"children": []
		}, {
			"value": "110115",
			"title": "大兴区",
			"children": []
		}, {
			"value": "110101",
			"title": "东城区",
			"children": []
		}, {
			"value": "110111",
			"title": "房山区",
			"children": []
		}, {
			"value": "110106",
			"title": "丰台区",
			"children": []
		}, {
			"value": "110108",
			"title": "海淀区",
			"children": []
		}, {
			"value": "110116",
			"title": "怀柔区",
			"children": []
		}, {
			"value": "110109",
			"title": "门头沟区",
			"children": []
		}, {
			"value": "110228",
			"title": "密云县",
			"children": []
		}, {
			"value": "110117",
			"title": "平谷区",
			"children": []
		}, {
			"value": "110230",
			"title": "其它区",
			"children": []
		}, {
			"value": "110107",
			"title": "石景山区",
			"children": []
		}, {
			"value": "110113",
			"title": "顺义区",
			"children": []
		}, {
			"value": "110112",
			"title": "通州区",
			"children": []
		}, {
			"value": "110102",
			"title": "西城区",
			"children": []
		}, {
			"value": "110104",
			"title": "宣武区",
			"children": []
		}, {
			"value": "110229",
			"title": "延庆县",
			"children": []
		}]
	}]
}, {
	"value": "450000",
	"title": "广西壮族自治区",
	"children": [{
		"value": "450500",
		"title": "北海市",
		"children": [{
			"value": "450502",
			"title": "海城区",
			"children": []
		}, {
			"value": "450521",
			"title": "合浦县",
			"children": []
		}, {
			"value": "450522",
			"title": "其它区",
			"children": []
		}, {
			"value": "450512",
			"title": "铁山港区",
			"children": []
		}, {
			"value": "450503",
			"title": "银海区",
			"children": []
		}]
	}, {
		"value": "451000",
		"title": "百色市",
		"children": [{
			"value": "451024",
			"title": "德保县",
			"children": []
		}, {
			"value": "451025",
			"title": "靖西县",
			"children": []
		}, {
			"value": "451028",
			"title": "乐业县",
			"children": []
		}, {
			"value": "451027",
			"title": "凌云县",
			"children": []
		}, {
			"value": "451031",
			"title": "隆林各族自治县",
			"children": []
		}, {
			"value": "451026",
			"title": "那坡县",
			"children": []
		}, {
			"value": "451023",
			"title": "平果县",
			"children": []
		}, {
			"value": "451032",
			"title": "其它区",
			"children": []
		}, {
			"value": "451022",
			"title": "田东县",
			"children": []
		}, {
			"value": "451029",
			"title": "田林县",
			"children": []
		}, {
			"value": "451021",
			"title": "田阳县",
			"children": []
		}, {
			"value": "451030",
			"title": "西林县",
			"children": []
		}, {
			"value": "451002",
			"title": "右江区",
			"children": []
		}]
	}, {
		"value": "451400",
		"title": "崇左市",
		"children": [{
			"value": "451424",
			"title": "大新县",
			"children": []
		}, {
			"value": "451421",
			"title": "扶绥县",
			"children": []
		}, {
			"value": "451402",
			"title": "江州区",
			"children": []
		}, {
			"value": "451423",
			"title": "龙州县",
			"children": []
		}, {
			"value": "451422",
			"title": "宁明县",
			"children": []
		}, {
			"value": "451481",
			"title": "凭祥市",
			"children": []
		}, {
			"value": "451482",
			"title": "其它区",
			"children": []
		}, {
			"value": "451425",
			"title": "天等县",
			"children": []
		}]
	}, {
		"value": "450600",
		"title": "防城港市",
		"children": [{
			"value": "450681",
			"title": "东兴市",
			"children": []
		}, {
			"value": "450603",
			"title": "防城区",
			"children": []
		}, {
			"value": "450602",
			"title": "港口区",
			"children": []
		}, {
			"value": "450682",
			"title": "其它区",
			"children": []
		}, {
			"value": "450621",
			"title": "上思县",
			"children": []
		}]
	}, {
		"value": "450800",
		"title": "贵港市",
		"children": [{
			"value": "450802",
			"title": "港北区",
			"children": []
		}, {
			"value": "450803",
			"title": "港南区",
			"children": []
		}, {
			"value": "450881",
			"title": "桂平市",
			"children": []
		}, {
			"value": "450821",
			"title": "平南县",
			"children": []
		}, {
			"value": "450882",
			"title": "其它区",
			"children": []
		}, {
			"value": "450804",
			"title": "覃塘区",
			"children": []
		}]
	}, {
		"value": "450300",
		"title": "桂林市",
		"children": [{
			"value": "450303",
			"title": "叠彩区",
			"children": []
		}, {
			"value": "450332",
			"title": "恭城瑶族自治县",
			"children": []
		}, {
			"value": "450327",
			"title": "灌阳县",
			"children": []
		}, {
			"value": "450331",
			"title": "荔浦县",
			"children": []
		}, {
			"value": "450322",
			"title": "临桂区",
			"children": []
		}, {
			"value": "450323",
			"title": "灵川县",
			"children": []
		}, {
			"value": "450328",
			"title": "龙胜各族自治县",
			"children": []
		}, {
			"value": "450330",
			"title": "平乐县",
			"children": []
		}, {
			"value": "450333",
			"title": "其它区",
			"children": []
		}, {
			"value": "450305",
			"title": "七星区",
			"children": []
		}, {
			"value": "450324",
			"title": "全州县",
			"children": []
		}, {
			"value": "450304",
			"title": "象山区",
			"children": []
		}, {
			"value": "450325",
			"title": "兴安县",
			"children": []
		}, {
			"value": "450302",
			"title": "秀峰区",
			"children": []
		}, {
			"value": "450311",
			"title": "雁山区",
			"children": []
		}, {
			"value": "450321",
			"title": "阳朔县",
			"children": []
		}, {
			"value": "450326",
			"title": "永福县",
			"children": []
		}, {
			"value": "450329",
			"title": "资源县",
			"children": []
		}]
	}, {
		"value": "451200",
		"title": "河池市",
		"children": [{
			"value": "451227",
			"title": "巴马瑶族自治县",
			"children": []
		}, {
			"value": "451229",
			"title": "大化瑶族自治县",
			"children": []
		}, {
			"value": "451224",
			"title": "东兰县",
			"children": []
		}, {
			"value": "451228",
			"title": "都安瑶族自治县",
			"children": []
		}, {
			"value": "451223",
			"title": "凤山县",
			"children": []
		}, {
			"value": "451226",
			"title": "环江毛南族自治县",
			"children": []
		}, {
			"value": "451202",
			"title": "金城江区",
			"children": []
		}, {
			"value": "451225",
			"title": "罗城仫佬族自治县",
			"children": []
		}, {
			"value": "451221",
			"title": "南丹县",
			"children": []
		}, {
			"value": "451282",
			"title": "其它区",
			"children": []
		}, {
			"value": "451222",
			"title": "天峨县",
			"children": []
		}, {
			"value": "451281",
			"title": "宜州市",
			"children": []
		}]
	}, {
		"value": "451100",
		"title": "贺州市",
		"children": [{
			"value": "451102",
			"title": "八步区",
			"children": []
		}, {
			"value": "451123",
			"title": "富川瑶族自治县",
			"children": []
		}, {
			"value": "451119",
			"title": "平桂管理区",
			"children": []
		}, {
			"value": "451124",
			"title": "其它区",
			"children": []
		}, {
			"value": "451121",
			"title": "昭平县",
			"children": []
		}, {
			"value": "451122",
			"title": "钟山县",
			"children": []
		}]
	}, {
		"value": "451300",
		"title": "来宾市",
		"children": [{
			"value": "451381",
			"title": "合山市",
			"children": []
		}, {
			"value": "451324",
			"title": "金秀瑶族自治县",
			"children": []
		}, {
			"value": "451382",
			"title": "其它区",
			"children": []
		}, {
			"value": "451323",
			"title": "武宣县",
			"children": []
		}, {
			"value": "451322",
			"title": "象州县",
			"children": []
		}, {
			"value": "451321",
			"title": "忻城县",
			"children": []
		}, {
			"value": "451302",
			"title": "兴宾区",
			"children": []
		}]
	}, {
		"value": "450200",
		"title": "柳州市",
		"children": [{
			"value": "450202",
			"title": "城中区",
			"children": []
		}, {
			"value": "450205",
			"title": "柳北区",
			"children": []
		}, {
			"value": "450222",
			"title": "柳城县",
			"children": []
		}, {
			"value": "450221",
			"title": "柳江县",
			"children": []
		}, {
			"value": "450204",
			"title": "柳南区",
			"children": []
		}, {
			"value": "450223",
			"title": "鹿寨县",
			"children": []
		}, {
			"value": "450227",
			"title": "其它区",
			"children": []
		}, {
			"value": "450224",
			"title": "融安县",
			"children": []
		}, {
			"value": "450225",
			"title": "融水苗族自治县",
			"children": []
		}, {
			"value": "450226",
			"title": "三江侗族自治县",
			"children": []
		}, {
			"value": "450203",
			"title": "鱼峰区",
			"children": []
		}]
	}, {
		"value": "450100",
		"title": "南宁市",
		"children": [{
			"value": "450126",
			"title": "宾阳县",
			"children": []
		}, {
			"value": "450127",
			"title": "横县",
			"children": []
		}, {
			"value": "450105",
			"title": "江南区",
			"children": []
		}, {
			"value": "450108",
			"title": "良庆区",
			"children": []
		}, {
			"value": "450123",
			"title": "隆安县",
			"children": []
		}, {
			"value": "450124",
			"title": "马山县",
			"children": []
		}, {
			"value": "450128",
			"title": "其它区",
			"children": []
		}, {
			"value": "450103",
			"title": "青秀区",
			"children": []
		}, {
			"value": "450125",
			"title": "上林县",
			"children": []
		}, {
			"value": "450122",
			"title": "武鸣区",
			"children": []
		}, {
			"value": "450107",
			"title": "西乡塘区",
			"children": []
		}, {
			"value": "450102",
			"title": "兴宁区",
			"children": []
		}, {
			"value": "450109",
			"title": "邕宁区",
			"children": []
		}]
	}, {
		"value": "450700",
		"title": "钦州市",
		"children": [{
			"value": "450721",
			"title": "灵山县",
			"children": []
		}, {
			"value": "450722",
			"title": "浦北县",
			"children": []
		}, {
			"value": "450723",
			"title": "其它区",
			"children": []
		}, {
			"value": "450703",
			"title": "钦北区",
			"children": []
		}, {
			"value": "450702",
			"title": "钦南区",
			"children": []
		}]
	}, {
		"value": "450400",
		"title": "梧州市",
		"children": [{
			"value": "450421",
			"title": "苍梧县",
			"children": []
		}, {
			"value": "450481",
			"title": "岑溪市",
			"children": []
		}, {
			"value": "450405",
			"title": "长洲区",
			"children": []
		}, {
			"value": "450404",
			"title": "蝶山区",
			"children": []
		}, {
			"value": "450406",
			"title": "龙圩区",
			"children": []
		}, {
			"value": "450423",
			"title": "蒙山县",
			"children": []
		}, {
			"value": "450482",
			"title": "其它区",
			"children": []
		}, {
			"value": "450422",
			"title": "藤县",
			"children": []
		}, {
			"value": "450403",
			"title": "万秀区",
			"children": []
		}]
	}, {
		"value": "450900",
		"title": "玉林市",
		"children": [{
			"value": "450981",
			"title": "北流市",
			"children": []
		}, {
			"value": "450923",
			"title": "博白县",
			"children": []
		}, {
			"value": "450903",
			"title": "福绵区",
			"children": []
		}, {
			"value": "450922",
			"title": "陆川县",
			"children": []
		}, {
			"value": "450982",
			"title": "其它区",
			"children": []
		}, {
			"value": "450921",
			"title": "容县",
			"children": []
		}, {
			"value": "450924",
			"title": "兴业县",
			"children": []
		}, {
			"value": "450902",
			"title": "玉州区",
			"children": []
		}]
	}]
}, {
	"value": "810000",
	"title": "香港特别行政区",
	"children": [{
		"value": "810200",
		"title": "九龙",
		"children": [{
			"value": "810205",
			"title": "观塘区",
			"children": []
		}, {
			"value": "810204",
			"title": "黄大仙区",
			"children": []
		}, {
			"value": "810201",
			"title": "九龙城区",
			"children": []
		}, {
			"value": "810203",
			"title": "深水埗区",
			"children": []
		}, {
			"value": "810202",
			"title": "油尖旺区",
			"children": []
		}]
	}, {
		"value": "810100",
		"title": "香港岛",
		"children": [{
			"value": "810103",
			"title": "东区",
			"children": []
		}, {
			"value": "810104",
			"title": "南区",
			"children": []
		}, {
			"value": "810102",
			"title": "湾仔",
			"children": []
		}, {
			"value": "810101",
			"title": "中西区",
			"children": []
		}]
	}, {
		"value": "810300",
		"title": "新界",
		"children": [{
			"value": "810301",
			"title": "北区",
			"children": []
		}, {
			"value": "810302",
			"title": "大埔区",
			"children": []
		}, {
			"value": "810308",
			"title": "葵青区",
			"children": []
		}, {
			"value": "810309",
			"title": "离岛区",
			"children": []
		}, {
			"value": "810307",
			"title": "荃湾区",
			"children": []
		}, {
			"value": "810303",
			"title": "沙田区",
			"children": []
		}, {
			"value": "810306",
			"title": "屯门区",
			"children": []
		}, {
			"value": "810304",
			"title": "西贡区",
			"children": []
		}, {
			"value": "810305",
			"title": "元朗区",
			"children": []
		}]
	}]
}, {
	"value": "330000",
	"title": "浙江省",
	"children": [{
		"value": "330100",
		"title": "杭州市",
		"children": [{
			"value": "330108",
			"title": "滨江区",
			"children": []
		}, {
			"value": "330127",
			"title": "淳安县",
			"children": []
		}, {
			"value": "330183",
			"title": "富阳区",
			"children": []
		}, {
			"value": "330105",
			"title": "拱墅区",
			"children": []
		}, {
			"value": "330182",
			"title": "建德市",
			"children": []
		}, {
			"value": "330104",
			"title": "江干区",
			"children": []
		}, {
			"value": "330185",
			"title": "临安市",
			"children": []
		}, {
			"value": "330186",
			"title": "其它区",
			"children": []
		}, {
			"value": "330102",
			"title": "上城区",
			"children": []
		}, {
			"value": "330122",
			"title": "桐庐县",
			"children": []
		}, {
			"value": "330106",
			"title": "西湖区",
			"children": []
		}, {
			"value": "330103",
			"title": "下城区",
			"children": []
		}, {
			"value": "330109",
			"title": "萧山区",
			"children": []
		}, {
			"value": "330110",
			"title": "余杭区",
			"children": []
		}]
	}, {
		"value": "330500",
		"title": "湖州市",
		"children": [{
			"value": "330523",
			"title": "安吉县",
			"children": []
		}, {
			"value": "330522",
			"title": "长兴县",
			"children": []
		}, {
			"value": "330521",
			"title": "德清县",
			"children": []
		}, {
			"value": "330503",
			"title": "南浔区",
			"children": []
		}, {
			"value": "330524",
			"title": "其它区",
			"children": []
		}, {
			"value": "330502",
			"title": "吴兴区",
			"children": []
		}]
	}, {
		"value": "330400",
		"title": "嘉兴市",
		"children": [{
			"value": "330481",
			"title": "海宁市",
			"children": []
		}, {
			"value": "330424",
			"title": "海盐县",
			"children": []
		}, {
			"value": "330421",
			"title": "嘉善县",
			"children": []
		}, {
			"value": "330402",
			"title": "南湖区",
			"children": []
		}, {
			"value": "330482",
			"title": "平湖市",
			"children": []
		}, {
			"value": "330484",
			"title": "其它区",
			"children": []
		}, {
			"value": "330483",
			"title": "桐乡市",
			"children": []
		}, {
			"value": "330411",
			"title": "秀洲区",
			"children": []
		}]
	}, {
		"value": "330700",
		"title": "金华市",
		"children": [{
			"value": "330783",
			"title": "东阳市",
			"children": []
		}, {
			"value": "330703",
			"title": "金东区",
			"children": []
		}, {
			"value": "330781",
			"title": "兰溪市",
			"children": []
		}, {
			"value": "330727",
			"title": "磐安县",
			"children": []
		}, {
			"value": "330726",
			"title": "浦江县",
			"children": []
		}, {
			"value": "330785",
			"title": "其它区",
			"children": []
		}, {
			"value": "330702",
			"title": "婺城区",
			"children": []
		}, {
			"value": "330723",
			"title": "武义县",
			"children": []
		}, {
			"value": "330782",
			"title": "义乌市",
			"children": []
		}, {
			"value": "330784",
			"title": "永康市",
			"children": []
		}]
	}, {
		"value": "331100",
		"title": "丽水市",
		"children": [{
			"value": "331122",
			"title": "缙云县",
			"children": []
		}, {
			"value": "331127",
			"title": "景宁畲族自治县",
			"children": []
		}, {
			"value": "331102",
			"title": "莲都区",
			"children": []
		}, {
			"value": "331181",
			"title": "龙泉市",
			"children": []
		}, {
			"value": "331182",
			"title": "其它区",
			"children": []
		}, {
			"value": "331121",
			"title": "青田县",
			"children": []
		}, {
			"value": "331126",
			"title": "庆元县",
			"children": []
		}, {
			"value": "331124",
			"title": "松阳县",
			"children": []
		}, {
			"value": "331123",
			"title": "遂昌县",
			"children": []
		}, {
			"value": "331125",
			"title": "云和县",
			"children": []
		}]
	}, {
		"value": "330200",
		"title": "宁波市",
		"children": [{
			"value": "330206",
			"title": "北仑区",
			"children": []
		}, {
			"value": "330282",
			"title": "慈溪市",
			"children": []
		}, {
			"value": "330283",
			"title": "奉化市",
			"children": []
		}, {
			"value": "330203",
			"title": "海曙区",
			"children": []
		}, {
			"value": "330205",
			"title": "江北区",
			"children": []
		}, {
			"value": "330204",
			"title": "江东区",
			"children": []
		}, {
			"value": "330226",
			"title": "宁海县",
			"children": []
		}, {
			"value": "330284",
			"title": "其它区",
			"children": []
		}, {
			"value": "330225",
			"title": "象山县",
			"children": []
		}, {
			"value": "330212",
			"title": "鄞州区",
			"children": []
		}, {
			"value": "330281",
			"title": "余姚市",
			"children": []
		}, {
			"value": "330211",
			"title": "镇海区",
			"children": []
		}]
	}, {
		"value": "330800",
		"title": "衢州市",
		"children": [{
			"value": "330822",
			"title": "常山县",
			"children": []
		}, {
			"value": "330881",
			"title": "江山市",
			"children": []
		}, {
			"value": "330824",
			"title": "开化县",
			"children": []
		}, {
			"value": "330802",
			"title": "柯城区",
			"children": []
		}, {
			"value": "330825",
			"title": "龙游县",
			"children": []
		}, {
			"value": "330882",
			"title": "其它区",
			"children": []
		}, {
			"value": "330803",
			"title": "衢江区",
			"children": []
		}]
	}, {
		"value": "330600",
		"title": "绍兴市",
		"children": [{
			"value": "330621",
			"title": "柯桥区",
			"children": []
		}, {
			"value": "330684",
			"title": "其它区",
			"children": []
		}, {
			"value": "330682",
			"title": "上虞区",
			"children": []
		}, {
			"value": "330683",
			"title": "嵊州市",
			"children": []
		}, {
			"value": "330624",
			"title": "新昌县",
			"children": []
		}, {
			"value": "330602",
			"title": "越城区",
			"children": []
		}, {
			"value": "330681",
			"title": "诸暨市",
			"children": []
		}]
	}, {
		"value": "331000",
		"title": "台州市",
		"children": [{
			"value": "331003",
			"title": "黄岩区",
			"children": []
		}, {
			"value": "331002",
			"title": "椒江区",
			"children": []
		}, {
			"value": "331082",
			"title": "临海市",
			"children": []
		}, {
			"value": "331004",
			"title": "路桥区",
			"children": []
		}, {
			"value": "331083",
			"title": "其它区",
			"children": []
		}, {
			"value": "331022",
			"title": "三门县",
			"children": []
		}, {
			"value": "331023",
			"title": "天台县",
			"children": []
		}, {
			"value": "331081",
			"title": "温岭市",
			"children": []
		}, {
			"value": "331024",
			"title": "仙居县",
			"children": []
		}, {
			"value": "331021",
			"title": "玉环县",
			"children": []
		}]
	}, {
		"value": "330300",
		"title": "温州市",
		"children": [{
			"value": "330327",
			"title": "苍南县",
			"children": []
		}, {
			"value": "330322",
			"title": "洞头县",
			"children": []
		}, {
			"value": "330303",
			"title": "龙湾区",
			"children": []
		}, {
			"value": "330302",
			"title": "鹿城区",
			"children": []
		}, {
			"value": "330304",
			"title": "瓯海区",
			"children": []
		}, {
			"value": "330326",
			"title": "平阳县",
			"children": []
		}, {
			"value": "330383",
			"title": "其它区",
			"children": []
		}, {
			"value": "330381",
			"title": "瑞安市",
			"children": []
		}, {
			"value": "330329",
			"title": "泰顺县",
			"children": []
		}, {
			"value": "330328",
			"title": "文成县",
			"children": []
		}, {
			"value": "330324",
			"title": "永嘉县",
			"children": []
		}, {
			"value": "330382",
			"title": "乐清市",
			"children": []
		}]
	}, {
		"value": "330900",
		"title": "舟山市",
		"children": [{
			"value": "330921",
			"title": "岱山县",
			"children": []
		}, {
			"value": "330902",
			"title": "定海区",
			"children": []
		}, {
			"value": "330903",
			"title": "普陀区",
			"children": []
		}, {
			"value": "330923",
			"title": "其它区",
			"children": []
		}, {
			"value": "330922",
			"title": "嵊泗县",
			"children": []
		}]
	}]
}];
